# Generated by Django 4.1.4 on 2024-12-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_alter_readinglist_options_readinglist_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('arts', 'ARTS'), ('games', 'GAMES'), ('home', 'HOME'), ('health', 'HEALTH'), ('technology', 'TECHNOLOGY'), ('recreation', 'RECREATION'), ('business', 'BUSINESS'), ('society', 'SOCIETY'), ('sports', 'SPORTS'), ('science', 'SCIENCE')], max_length=20),
        ),
    ]
